### PR TITLE
Build for CentOS 8

### LINKED ISSUE #40: Request build for CentOS 8

### PR DESCRIPTION
**Pull request by pedrofurtado**
Closes #40

@ashkulz I don't know if just this change is enough for build in CentOS 8. Could you help me? 😆 👍

### CODE REVIEW

**Comment by ashkulz** [comment]
@pedrofurtado: you'll need to add a new section, not change the CentOS 7 sections. You can check if it works locally in two steps:
* **build image**: `./build docker-images centos8-x86_64` -- this will just build it locally
* **package**: `./build package-docker centos8-x86_64 ~/wkhtmltopdf` (assuming you have a full clone of wkhtmltopdf, with the patched Qt in `~/wkhtmltopdf`).

If you get any errors, you'll have to adjust the configuration (e.g. package names might be slightly different in CentOS 8.

**Comment by dnorgaard-usgs** [comment]
Running into below issue on trying to build package:

 ./build package-docker centos8-x86_64 ~/wkhtmltopdf
Traceback (most recent call last):
  File "./build", line 297, in <module>
    main()
  File "./build", line 294, in main
    func(yaml.load(f.read()), **args)
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 114, column 71:
     ... r-bar top-0 left-0" style="width: 0%;"></span>
                                         ^

**Comment by pedrofurtado** [comment]
@ashkulz Could you help us? I'm not familiar with the build process, I am a little bit confused :laughing:

**Comment by ashkulz** [comment]
With the latest branch, it seems to build the docker image -- currently running the compilation, but I don't expect a failure there. Not sure about the error @dnorgaard-usgs is facing, can you provide more details of the host OS?

**Comment by ashkulz** [comment]
A [CentOS 8 rpm](https://builds.wkhtmltopdf.org/wkhtmltox-0.12.5-1.centos8.x86_64.rpm) was built with this branch, can someone check if it works correctly?

**Comment by dnorgaard-usgs** [comment]
Do I need to install dependencies separately?

[dnorgaard@web ~]$ sudo rpm -i wkhtmltox-0.12.5-1.centos8.x86_64.rpm
error: Failed dependencies:
        libXext is needed by wkhtmltox-1:0.12.5-1.centos8.x86_64
        libXrender is needed by wkhtmltox-1:0.12.5-1.centos8.x86_64
        xorg-x11-fonts-75dpi is needed by wkhtmltox-1:0.12.5-1.centos8.x86_64
        xorg-x11-fonts-Type1 is needed by wkhtmltox-1:0.12.5-1.centos8.x86_64

**Comment by dnorgaard-usgs** [comment]
I installed the dependencies manually and was able to install wkhtmltopdf and test that it worked.  Thanks!

**Comment by ashkulz** [comment]
Thanks for the contribution, @pedrofurtado!

**Comment by pedrofurtado** [comment]
@ashkulz Thanks for merging! And thanks to everybody that contribute in this PR, with debug informations and so on 🤝 🥇 

@ashkulz Some doubts:

1 - It will be released a new version, to provide officially the 0.12.5 version for CentOS 8?
2 - Where do I modify the docs (of this page -> https://wkhtmltopdf.org/downloads.html ), to provide links to CentOS 8 binary? Is this a Github repo?

**Comment by ashkulz** [comment]
I'm currently building the packages for `buster` and `centos8`, have to find the GPG key so that I resign the SHA256SUMS. The file is [over here](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/docs/downloads.md) in the main repo, I'll push a commit once I've done that.

**Pull request merged**
