### PR TITLE
Crate google cloud functions package

### PR DESCRIPTION
**Pull request by batosti**
Create a google cloud function package to use with google serverless functions

### CODE REVIEW

**Comment by ashkulz** [comment]
@batosti, thanks for the contribution! I assume you have tested this and it works? I'd also appreciate a PR on the main repo with docs on how to use this package.

**Comment by batosti** [comment]
Yes, it's working fine, I'll produce the docs and send another pull request.

Thanks a lot

Em qui., 1 de abr. de 2021 01:09, Ashish Kulkarni ***@***.***>
escreveu:

**Comment by ashkulz** [comment]
Did you get a chance to do that?

**Comment by batosti** [comment]
Not yet,

On last saturday my new daughter was born and I didn't work yet. Today
that's I trying to read all emails and get the pending work done.

Regards,
André Batosti
***@***.***

"No man is a failure who is enjoying life."

**Comment by ashkulz** [comment]
Hey congratulations! I can certainly understand your taking some time during such a life-changing event :tada:

**Comment by ashkulz** [comment]
@batosti I'm planning to make a new release (`0.12.6.1`) soon, if you find time to work on this feel free to open it again and address the feedback.

**Pull request closed without merging**
