### PR TITLE
Support Ubuntu 22.04 Jammy Jellyfish

### PR DESCRIPTION
**Pull request by pfumagalli**
The new Ubuntu LTS 22.04 was released on 21 April 2022, this small patch enables support for it.

### CODE REVIEW

**Comment by ashkulz** [comment]
@pfumagalli does this work? I think you need to have some patches for Qt 4 for it to compile.

**Comment by pfumagalli** [comment]
Huh???

You patched it last week!

https://github.com/wkhtmltopdf/qt/commit/bb81921302fec10702d0d864d8d440fa0fe91900

**Comment by ashkulz** [comment]
That's exactly what I meant, but it's not part of any official release yet. I'm working on Ubuntu 22.04 and Debian 11 support, but haven't gotten time to finish porting to GH Actions.

I think it should work with gcc10, not sure why you used gcc9?

**Comment by pfumagalli** [comment]
I needed a version of 0.12.5 for ARM64, running on Jammy (installing Odoo on Graviton) so I cherry picked bb81921, ac069f4, 61e4464, and 7480f44 on my tree and compiled...

I used GCC 9 because when I started (before your commits) I was using https://aur.archlinux.org/cgit/aur.git/tree/qt4-gcc9.patch?h=qt4 and felt it was the _safest_ option. I haven't tried 10 or 11 (Jammy's default).

**Comment by chrira** [comment]
This PR would fix #114 
We are also looking forward to get a release for Ubuntu 22.04 (jammy)

**Comment by ashkulz** [comment]
I'm first trying to move to GitHub Actions, after which I can look at this and #101

**Comment by ashkulz** [comment]
Thanks for the contribution, @pfumagalli! I've [started building the packages](https://github.com/wkhtmltopdf/packaging/actions/runs/2542955342) and hopefully should be published by tomorrow :+1:

**Comment by ashkulz** [comment]
Builds have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff.

**Pull request closed without merging**
